### ISSUE TITLE
Add support for tsvector type in the Postgres plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-jdbc#283]
### Feature description

If you do `SELECT * FROM mytable` and the table has a `tsvector` column, you'll get an error:

```Java
Starting query: SELECT *
FROM executions
ORDER BY end_date DESC
LIMIT 100;
2024-04-21 15:05:21.527PGobject of type [tsvector] is not supported
2024-04-21 15:05:21.527java.lang.IllegalArgumentException: PGobject of type [tsvector] is not supported
	at io.kestra.plugin.jdbc.postgresql.PostgresCellConverter.convertCell(PostgresCellConverter.java:75)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.convertCell(AbstractJdbcQuery.java:189)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.mapResultSetToMap(AbstractJdbcQuery.java:182)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.fetch(AbstractJdbcQuery.java:167)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.fetchToFile(AbstractJdbcQuery.java:148)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.run(AbstractJdbcQuery.java:109)
	at io.kestra.plugin.jdbc.postgresql.Query.run(Query.java:21)
	at io.kestra.core.runners.WorkerTaskThread.run(WorkerTaskThread.java:58)
```

**Comment by loicmathieu** [comment]
Fixed in https://github.com/kestra-io/plugin-jdbc/pull/361
