### ISSUE TITLE
ClickHouse plugin does not support UInt64 data type

### ISSUE THREAD

**Issue by aku** [kestra-io/plugin-jdbc#332]
### Describe the issue

If you try to return a UInt64 column an error happens:

```
Data of type 'class com.clickhouse.data.value.UnsignedLong' for column '[REDACTED]' is not supported
```

```
java.lang.IllegalArgumentException: Data of type 'class com.clickhouse.data.value.UnsignedLong' for column '[REDACTED]' is not supported
	at io.kestra.plugin.jdbc.AbstractCellConverter.convert(AbstractCellConverter.java:81)
	at io.kestra.plugin.jdbc.clickhouse.ClickHouseCellConverter.convertCell(ClickHouseCellConverter.java:88)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.convertCell(AbstractJdbcQuery.java:189)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.mapResultSetToMap(AbstractJdbcQuery.java:182)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.fetchResult(AbstractJdbcQuery.java:140)
	at io.kestra.plugin.jdbc.AbstractJdbcQuery.run(AbstractJdbcQuery.java:102)
	at io.kestra.plugin.jdbc.clickhouse.Query.run(Query.java:58)
	at io.kestra.plugin.jdbc.clickhouse.Query.run(Query.java:21)
	at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:77)
	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:56)
```

As a temporary solution I use toInt64 function to convert from UInt64 to Int64 but it would be nice if you can fix it.

### Environment

- Kestra Version: 0.17.1
- Operating System (OS/Docker/Kubernetes): all
- Java Version (if you don't run kestra in Docker):

**Comment by mgabelle** [comment]
Fixed in : https://github.com/kestra-io/plugin-jdbc/pull/419
